project_id = "urczlhjnztiaxdsatueu"

[functions.send-invitation-emails]
verify_jwt = false

[functions.business-api]
verify_jwt = false

[functions.process-image-16x9]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = false

[functions.generate-placeholders]
verify_jwt = false

[functions.voucher-scheduler]
verify_jwt = false

[functions.send-analytics-report]
verify_jwt = false

[functions.post-to-social-media]
verify_jwt = false