// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htrpclvbgulwdjvrjaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhodHJwY2x2Ymd1bHdkanZyamFxbSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUxNzk1MjA1LCJleHAiOjIwNjczNzEyMDV9.fz-1ddlGQHfpKrTB3kOlMPP_Lhn0gOApIQG42sSJ8pE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});